INSERT INTO developers(name,age,gender,salary) VALUES ('Alexander',29,'male',8000);
INSERT INTO developers(name,age,gender,salary) VALUES ('Anna',23,'female',6000);
INSERT INTO developers(name,age,gender,salary) VALUES ('Alex',30,'male',9000);
INSERT INTO skill (language,level_skill) VALUES('Java','Senior');
INSERT INTO skill (language,level_skill) VALUES('Js','Middle');
INSERT INTO skill (language,level_skill) VALUES ('C#','Middle');
INSERT INTO skill (language,level_skill) VALUES ('C++','Junior');
INSERT INTO skill (language,level_skill) VALUES ('Java','Middle');
INSERT INTO developers_skill (developer_id,skill_id) VALUES (1,1);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (1,3);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (2,2);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (2,5);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (3,4);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (3,2);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (3,1);
INSERT INTO companies (name_companies,country_companies) VALUES ('Dell Technologies','USA');
INSERT INTO companies (name_companies,country_companies) VALUES ('EPAM','Ukraine');
INSERT INTO companies (name_companies,country_companies) VALUES ('Samsung','Korea');
INSERT INTO customers (name_customers,country_customers) VALUES ('customer_1','Ukraine');
INSERT INTO customers (name_customers,country_customers) VALUES ('customer_2','USA');
INSERT INTO customers (name_customers,country_customers) VALUES ('customer_3','Korea');
INSERT INTO customers (name_customers,country_customers) VALUES ('customer_4','Japan');
INSERT INTO projects (name_projects,companies_id,customers_id,start_project,cost_project) VALUES ('project_1',1,1,'2020-01-01',10000000);
INSERT INTO projects (name_projects,companies_id,customers_id,start_project,cost_project) VALUES ('project_2',1,2,'2010-09-01',2000000);
INSERT INTO projects (name_projects,companies_id,customers_id,start_project,cost_project) VALUES ('project_3',2,1,'2015-02-05',5000000);
INSERT INTO projects (name_projects,companies_id,customers_id,start_project,cost_project) VALUES ('project_4',2,2,'2009-05-02',1000000);
INSERT INTO projects (name_projects,companies_id,customers_id,start_project,cost_project) VALUES ('project_5',3,3,'2014-04-01',3000000);
INSERT INTO projects (name_projects,companies_id,customers_id,start_project,cost_project) VALUES ('project_6',3,3,'2007-03-07',1000000);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (1,1);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (2,5);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (3,6);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (2,2);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (3,2);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (1,3);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (3,4);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (2,4);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (2,1);